import { combineReducers } from 'redux';
import {
  news,
  movie,
  search,
  rating,
  cinema,
  cinemas,
  loading,
  ratings,
  article,
  promo,
  action,
  movies,
  reviews,
  seoInfo,
  articles,
  overview,
  cinemaApps,
  cinemaPrice,
  cinemaAppInfo,
  cinemaFeatures,
  catalogFilters,
  cinemaAchievement,
  articleCategories,
  cinemaTrustedSource,
} from '../../store/reducers';

export default combineReducers({
  news,
  movie,
  movies,
  promo,
  action,
  article,
  articles,
  cinemas,
  cinema,
  seoInfo,
  overview,
  catalogFilters,
  cinemaFeatures,
  cinemaPrice,
  cinemaApps,
  articleCategories,
  cinemaTrustedSource,
  cinemaAppInfo,
  cinemaAchievement,
  ratings,
  rating,
  loading,
  reviews,
  search,
});
